name: transmap_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  VERSIONES OLDS
#  cupertino_icons: ^0.1.2
#  http: ^0.12.0+4
#  easy_localization: ^2.0.2
#  flutter_svg: ^0.18.0
#  autocomplete_textfield: ^1.7.3
#  flutter_typeahead: ^1.7.0
#  snack: ^1.0.4
#  shared_preferences: ^0.5.6+3
#  marquee_flutter: ^0.1.3
#  pdf: ^2.1.0
#  path_provider: ^1.6.28
  http: 0.13.4
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.1+1
  autocomplete_textfield: ^2.0.1
#  flutter_typeahead: ^4.3.2
  flutter_typeahead: ^4.3.1
  snack: ^2.0.0
  shared_preferences: any
#  marquee_flutter: ^0.1.3
  pdf: ^3.8.2
  path_provider: ^2.0.11
  awesome_dialog: 2.2.1
#  sqflite: ^2.0.3+1
  path: 1.8.1
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.2
  lottie: 1.4.2
  line_icons: ^2.0.3
#  flutter_tags: ^0.4.9+1
  flutter_tags: 1.0.0-nullsafety.0


#   3.0.3 # SE QUITA DESDE LA VERSION 1.0.12 POR USO DE INSTALADOR DE PAQUETES

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/animation/
    - assets/wallpapers/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
